### ISSUE TITLE
提issus，界面好看，建议input format控制或者提示，还有可以添加待扫描域名

### ISSUE THREAD

**Issue by hkzck** [Cl0udG0d/SZhe_Scan#10]
添加任务
![image](https://user-images.githubusercontent.com/48936012/87097694-50760f80-c278-11ea-8880-5e0c17c74846.png)
这里，每次只能添加一个吗，还是啥

建议对输入得到域名format优化一下

**Comment by Cl0udG0d** [comment]
不是每次添加一个哈，可以同时输入多个的，每行输入一个扫描的URL即可，输入的目标格式可为：  
127.0.0.1
http://127.0.0.1
www.baidu.com
https://www.baidu.com
然后得到域名format格式化优化是啥意思哇，没咋看懂这句

**Comment by Cl0udG0d** [comment]
欢迎使用新版 :)
