### ISSUE TITLE
再提issus,新功能

### ISSUE THREAD

**Issue by hkzck** [Cl0udG0d/SZhe_Scan#11]
还可以增加  漏洞及时通知反馈功能

结果发送给server酱
或者微信公众号，或者钉钉等等

这样感觉能及时知道结果

**Comment by hkzck** [comment]
再提一个批量添加扫描目标，这个肯定要的
输入提示或者文档啥的整一个

**Comment by Cl0udG0d** [comment]
嗯嗯，后面会考虑添加及时反馈通知功能的，是可以批量扫描的。然后输入提示确实没整，过两天整上去

**Comment by hkzck** [comment]
> 嗯嗯，后面会考虑添加及时反馈通知功能的，是可以批量扫描的。然后输入提示确实没整，过两天整上去
okkkkk

**Comment by hkzck** [comment]
后面的确是发现了可以批量，哈哈

**Comment by Cl0udG0d** [comment]
欢迎使用新版呀 :)
