### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XTeam-Wing** [Cl0udG0d/SZhe_Scan#12]
建议资产扫描做成分布式扫描,否则单机扫描目标的全端口在时间上就行不通.我的漏扫功能是可以全选插件扫描或指定插件扫描,好处就是新的漏洞出来先测试一遍.功能模块分开的同时也能关联起来.

**Comment by Cl0udG0d** [comment]
好的，后面是准备弄成分布式的，但是现在扫描系统还有一些主要的问题没有解决，准备先解决了主要问题之后再弄成分布式，以及准备先通过nmap参数的调整来缓解全端口扫描时间上的问题： -Pn -sV --open -T3 -n --host-timeout=60s --min-rate=500
阿里嘎多

**Comment by Cl0udG0d** [comment]
欢迎使用新版呀 :)
