### ISSUE TITLE
成功运行，但是瑕疵还比较多

### ISSUE THREAD

**Issue by sDreamForZzQ** [Cl0udG0d/SZhe_Scan#13]
用了一下感觉误报还是太多了，报出很多xss根本就没有参数输入的地方并且payload中还插着日期，emmmmmm，还有高危的洞是js文件后边跟了命令注入的payload，但是并没有办法传参，而且有的完全相同的漏洞会重复报很多次。

**Comment by Cl0udG0d** [comment]
嗯嗯，漏洞误报，重复漏洞的过滤都是需要完善的地方，我们会努力减少这些瑕疵的！

**Comment by Cl0udG0d** [comment]
欢迎使用新版 :)
