### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by J0o1ey** [Cl0udG0d/SZhe_Scan#14]
您好师傅，成功在服务器上通过源码搭建了，但是只能本地访问，外网访问会直接拒绝请求（已经放行所有端口），请问怎么进行配置使得外网可以访问

**Comment by Cl0udG0d** [comment]
您好，给你看一下我阿里云服务器设置的安全组规则：
![image](https://user-images.githubusercontent.com/45556496/88533579-1ad37380-d039-11ea-8ee0-87fde98f9700.png)
你应该只需要设置红框标记的那个，只用设置入方向就行啦。
如果还不行的话麻烦再留言哈
