### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by Ershu1** [Cl0udG0d/SZhe_Scan#19]
搭建成功了， 能够运行，还是很不错的。
1. 希望能够优化一下漏洞误报，能够点选想查找类型的漏洞和漏洞分级查看
2. 漏洞类型统计的那个地方的百分比显示，可以移到进度条右端，现在看着有点遮挡
    扫描进度那里也是
3. 能够取消添加的任务
4. 明明扫描完成了，还是显示待扫描。

**Comment by Cl0udG0d** [comment]
欢迎使用新版呀 :)
