### ISSUE TITLE
docker版有戏了不？

### ISSUE THREAD

**Issue by littleheary** [Cl0udG0d/SZhe_Scan#2]
斗胆问大佬，docker版有戏了不？

**Comment by Cl0udG0d** [comment]
学渣回校之后作业繁重，勉强活着已是万幸，但还是应大师傅要求，今晚熬夜全力将其项目打包并进一步测试后，明晚12点之前推出docker版，可好？

**Comment by Cl0udG0d** [comment]
呼，总算是弄好了，不过时间比较匆忙，项目里面仍然有很多不足的地方，希望大师傅多提issue，Docker已打包好，这两天有空的时候重写readme文档，Docker安装方法(依次输入这三条命令):
git clone git@github.com:Cl0udG0d/SZhe_Scan.git
cd SZhe_Scan
docker-compose up –d

睡了睡了，明天还有英语课

**Comment by Cl0udG0d** [comment]
(捂脸，忘说了
默认登录邮箱是:springbird@qq.com
密码是:springbird
