### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by fengxi-gyn** [Cl0udG0d/SZhe_Scan#24]
1.能直接看高危危险的漏洞，而不是显示有漏洞，打开一看几千条
2.能取消任务，而不是每次扫一半就卡主了
3.扫出来的漏洞能单独存放

**Comment by Cl0udG0d** [comment]
目前新版是在某个任务下查看其漏洞，会考虑根据漏洞等级分类的建议

取消任务已经实现

欢迎使用新版呀 :)
