### ISSUE TITLE
docker安装启动，登录后500

### ISSUE THREAD

**Issue by dead5nd** [Cl0udG0d/SZhe_Scan#3]
![image](https://user-images.githubusercontent.com/29460919/84162950-88d0d500-aaa3-11ea-899a-836baadd8390.png)

![image](https://user-images.githubusercontent.com/29460919/84162887-79518c00-aaa3-11ea-8a18-abcb93a5b814.png)

**Comment by Cl0udG0d** [comment]
不好意思啊，之前一直在写期末课程设计的报告和文档，所以现在才回复。
如果是想要检查错误的原因，启动docker时可以不加-d参数，这样能够不在后台运行，从而看到报错的原因，即启动docker 时使用命令：
docker-compose up
或者是导出docker的log日志进行查看错误
不过我个人感觉你出现这个错误的原因是数据库中某些表没有正确创建，究其根本或许是因为下载python库的时候访问国外网站导致部分包的丢失，为了能够更快地解决这个问题，建议你先删除掉本地docker镜像，修改SZhe_Scan文件夹下的Dockerfile文件
原来的Dockerfile文件里有一句:
RUN pip install -r requirements.txt
假设你有Linux基础哈，没有也没关系，修改文件很简单的，查一下就行了，修改上面那一句为：
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
也就是将python下载的源转至国内。
我不认为这是错误哈，因为下载源在国内或者国外，都各有好处吧，只是一个取舍罢了。
将其改过来之后再使用：
docker-compose up -d
应该就能够正常运行了
cheer，祝你愉快

**Comment by dead5nd** [comment]
hello,看了一下好像是redis镜像创建有问题,6379端口访问被拒绝了...
![image](https://user-images.githubusercontent.com/29460919/84218691-81401900-ab01-11ea-81a0-043928108013.png)

**Comment by EmptyZeroRain** [comment]
数据库连接不上
`
![QQ图片20200610113827](https://user-images.githubusercontent.com/48972652/84224374-efd7a380-ab0e-11ea-96b7-4b7d76dbd8b1.png)

**Comment by Cl0udG0d** [comment]
刚才我在另一台云服务器上部署成功了，然后将源码Dockerfile文件中pip下载源改回到了国内。如果你们这个问题还没有解决的话，就请将之前的docker镜像删除掉，然后下载最新的github源码，按照之前的部署方式重新部署，应该就可以了，祝好

**Comment by dead5nd** [comment]
可以啦，如果遇到错误就多docker-compose up 几次

**Comment by Cl0udG0d** [comment]
好的，那我把这个issue关闭了哈 👯

**Comment by dead5nd** [comment]
好的
