### ISSUE TITLE
使用文档打球不开

### ISSUE THREAD

**Issue by wjl110** [Cl0udG0d/SZhe_Scan#32]

**Comment by Cl0udG0d** [comment]
![image](https://user-images.githubusercontent.com/45556496/154883086-2d16d3c3-af78-4a39-98fc-9bdf6fc2be29.png)
![image](https://user-images.githubusercontent.com/45556496/154883100-967780d1-4087-4627-94e7-b88d7fc6e3b8.png)
虽然新版本的文档还没写完，但是我这边是能打开的，应该是你没开代理吧

**Comment by wjl110** [comment]
我没开代理
