### ISSUE TITLE
成功部署运行

### ISSUE THREAD

**Issue by iforensic99** [Cl0udG0d/SZhe_Scan#4]
mac环境下用docker成功搭建运行起来了，棒棒哒
不过测试了一下有几个小想法：
1、新建任务栏和预览图有点不太一样，输入链接后可以新建任务，不过感觉还缺一个任务列表，这样待扫描、已扫描就一目了然了，不然总有几个待扫描任务不知道为啥进行不下去；
![image](https://user-images.githubusercontent.com/66558535/84267780-3520c300-ab59-11ea-8758-05d4c7abb248.png)

2、控制台里预留的统计信息按钮点不了，如果能点进查看详情就完美了；
![image](https://user-images.githubusercontent.com/66558535/84267835-51246480-ab59-11ea-9509-af9e8c7a067a.png)

3、扫描过程考虑设置个进度条？可以根据需要随时终止扫描就好了
4、扫描结果考虑生成报告文件导出么。比如html格式或者pdf格式
5、作者的头像很帅，不过都比较适合女孩子啊，囧。要是新注册账号也能修改头像就好了。注册的时候没提示成功，不过多试几次就可以了。

**Comment by Cl0udG0d** [comment]
好的，会在两周内添加这些功能，因为要期末考试了，所以完善时间稍微说长点 :D

**Comment by littleheary** [comment]
部署好了，这个页面不会用啊 。

**Comment by Cl0udG0d** [comment]
确实，是我们readme里面没有写清楚使用的方法，晚上更新的时候修改readme，在控制台界面的新建任务里面每行输入一个url就行了，形如:
http://www.baidu.com
www.baidu.com
127.0.0.1
http://127.0.0.1
都可

**Comment by Cl0udG0d** [comment]
欢迎使用新版 :)
