### ISSUE TITLE
能否弄个管理待扫描目标的地方？

### ISSUE THREAD

**Issue by Third-rate** [Cl0udG0d/SZhe_Scan#5]
安裝成功了，弄了一批域名进行扫描，扫描到第6个的时候卡住了，几个小时都是那个目标，没有地方查看当前进度及管理待扫描不目标，就有点难受，连取消都没地方取消，像我这样，卡住在某个域名不动了，就完全没有任何办法

**Comment by Cl0udG0d** [comment]
好的哈，该功能在两周内会完成的，嘿嘿

**Comment by chengyizhou147** [comment]
感觉很棒，如果能取消扫描就更好了，加油！

**Comment by Cl0udG0d** [comment]
好的哈哈哈，正在暴打开发小姐姐了

**Comment by Cl0udG0d** [comment]
新版本已经添加该功能，欢迎使用:)
