### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by just805** [Cl0udG0d/SZhe_Scan#6]
建议作者在docker  pip源中用国内的源，https://pypi.tuna.tsinghua.edu.cn/simple/我试了很多次有些请求无法访问，可能导致安装出现其它错误。

**Comment by Cl0udG0d** [comment]
好的，我记得在pip中的源已经修改了：
![image](https://user-images.githubusercontent.com/45556496/84475039-7383c280-acbe-11ea-8790-41ec15d260df.png)
感觉还需要改一下docker apt下载的源为国内的。
欢迎加入项目问题反馈群哈:672408351

**Comment by Cl0udG0d** [comment]
在更新的版本中将docker apt源改为了国内镜像源，同时python pip安装库文件时也使用的国内镜像源，以加快部署的速度，相信因为网络和wall的原因而导致部署出现奇奇怪怪问题的情况会减少:
![image](https://user-images.githubusercontent.com/45556496/85317974-d4e33700-b4f1-11ea-89eb-a7a5964ee154.png)
老哥我把这个issue关闭了哈
