### ISSUE TITLE
docker版安装后登陆报错

### ISSUE THREAD

**Issue by littleheary** [Cl0udG0d/SZhe_Scan#7]
docker版安装完成以后，运行起来。
登陆进去报500

服务器挂了，正在暴打开发人员中^_^你被丢到火星了，送只猫咪陪你以表慰问Go Home

报错如下：
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'SZheScan.log' doesn't exist")
[SQL: INSERT INTO log (ip, email, date) VALUES (%(ip)s, %(email)s, %(date)s)]
[parameters: {'ip': '1.1.2.100', 'email': 'springbird@qq.com', 'date': datetime.datetime(2020, 6, 15, 3, 34, 18, 154845)}]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by littleheary** [comment]
是我自己的问题，解决掉了。

**Comment by Cl0udG0d** [comment]
嘿嘿，没事，我本来想等会再更新一次，把docker apt源修改了，再回复你的，然后你就自己弄好了，cheer!!

**Comment by DeepSec-BJTU** [comment]
> 是我自己的问题，解决掉了。

我也遇到同样问题，报同样的错误，是需要自己创建SZheScan.log么？

**Comment by Cl0udG0d** [comment]
> > 是我自己的问题，解决掉了。
> 
> 我也遇到同样问题，报同样的错误，是需要自己创造SZheScan.log么？

不需要，显示log表不存在报错，实际上应该是所有的表都都没有创建成功，只是因为log表第一个被用到，在登陆的时候会记录下用户的登录日志信息，所以会出错显示log表不存在，小姐姐们现在还没有找到为什么大家老是创建不了表的原因，考完试之后我们会仔细找一下，不好意思。如果没有log表的话建议将原来的容器镜像删除，然后重新compose-up试试趴
