### ISSUE TITLE
运行成功了

### ISSUE THREAD

**Issue by zhangyijie** [Cl0udG0d/SZhe_Scan#8]
有几个建议：
1.扫描不到那种需要登录的网站
2.不知道能不能提供扫描选项，我只想扫某个网站的SQL注入漏洞，和XSS
3.后期会加入扫描暗链和恶意关键字的功能吗

**Comment by Cl0udG0d** [comment]
你好，建议我们会逐渐加入扫描器功能中：
1，后期添加cookie或者输入用户名密码后对网站进行扫描
2，会添加扫描选项，时间在两周内
3，可以加入扫描暗链和恶意关键字的功能，这个暂时还没想到咋实现比较好，但是开发小姐姐会想办法的

以上，谢谢:D

**Comment by Cl0udG0d** [comment]
欢迎使用新版 :)
